apiVersion: 1

datasources:
  - name: mf-go Postgres
    uid: mfgo-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: masterfabric
    isDefault: true
    editable: false
    jsonData:
      database: masterfabric
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: masterfabric
